development:
  adapter: postgresql
  encoding: unicode
  database: blog_app_development
  pool: 5
  username: postgres
  password: root
  host: localhost
 
test:
  adapter: postgresql
  encoding: unicode
  database: blog_app_test
  pool: 5
  username: postgres 
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: blog_app_production
  pool: 5
  username: postgres
  password: root
  host: localhost